module.exports = {
  USER_LOGIN_REQUEST_SUCCESS: "USER_LOGIN_REQUEST_SUCCESS",
  USER_LOGIN_REQUEST_FAIL: "USER_LOGIN_REQUEST_FAIL",
  USER_REGISTER_REQUEST_SUCCESS: "USER_REGISTER_REQUEST_SUCCESS",
  USER_REGISTER_REQUEST_FAIL: "USER_REGISTER_REQUEST_FAIL",
  GET_USER_LIST_REQUEST_SUCCESS: "GET_USER_LIST_REQUEST_SUCCESS",
  SUCCESS_ALERT: "SUCCESS_ALERT",
  ERROR_ALERT: "ERROR_ALERT",
};
